#!/bin/bash
#
# usage: sfox <name> ...

set -ue

: ${FIREFOX:=$HOME/firefox/firefox}
: ${SFOXDIR:=$HOME/.sfox}
: ${SFOXGEOMETRY:=1024x768}
: ${SFOXWM:=metacity}

RESET=0

usage() {
	cat <<-EOF
	$0: usage: ${0##*/} [ --geometry <geometry> ] [ --reset ] name [...args...]

	--geometry (-g) - size of virtual framebuffer
	--window-manager (-w) - use a window manager other than metacity
	--reset - remove and re-create sandbox home directory

	[...args...] - any valid Firefox command line arguments
	EOF
}

if [[ -f $SFOXDIR/config ]]; then
	. $SFOXDIR/config
fi

while [[ $# -gt 0 ]]; do
	case $1 in
	(-g|--geometry)
		SFOXGEOMETRY=$2
		shift 2
		;;

	(-w|--window-manager)
		SFOXWM=$2
		shift 2
		;;

	(--reset)
		RESET=1
		shift
		;;

	(--help)
		shift
		usage
		exit 0
		;;

	(--)	shift
		break
		;;

	(-*)	echo "ERROR: unknown option: $1" >&2
		usage >&2
		exit 2
		;;

	(*)	break
		;;
	esac
done

if [[ $# -lt 1 ]]; then
	usage >&2
	exit 2
fi

name=$1
shift

SFHOME=$SFOXDIR/home/$name
if [[ $RESET = 1 ]]; then
	rm -rf $SFHOME
fi
mkdir -p $SFHOME

if ! [ -d $SFHOME/Downloads ]; then
	ln -sf $HOME/Downloads $SFHOME/Downloads
fi

cat > $SFHOME/.xbindkeysrc <<EOF
"dmenu_run"
  alt + shift + r
EOF

cat > $SFHOME/xinitrc <<EOF
#!/bin/sh

$SFOXWM &
xbindkeys &
$FIREFOX $*
EOF

chmod 755 $SFHOME/xinitrc

export HOME=$SFHOME
exec startx $SFHOME/xinitrc -- \
	/usr/bin/Xephyr -screen $SFOXGEOMETRY -terminate \
	>& /dev/null
